version: '3.1'

services:
  mongo:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: blogpwd
      INIT_WAIT_SEC: 3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/var/app/db
